import { useState, useEffect } from 'react'
import { reportsService } from '../services/reports'
import { useAuth } from '../hooks/useAuth'

export default function MyReports() {
  const [reports, setReports] = useState([])
  const [loading, setLoading] = useState(true)
  const { user } = useAuth()

  const generatePDFReport = () => {
    const reportData = {
      user: user?.user_metadata?.name || 'CivIQ User',
      email: user?.email || '',
      city: user?.user_metadata?.city || '',
      reports: reports,
      generatedAt: new Date().toLocaleString(),
      totalReports: reports.length,
      totalPoints: reports.reduce((sum, report) => sum + (report.points_awarded || 15), 0),
      resolvedReports: reports.filter(r => r.status === 'resolved').length
    }

    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>CivIQ Issue Reports - ${reportData.user}</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
          .header { text-align: center; border-bottom: 2px solid #2563eb; padding-bottom: 20px; margin-bottom: 30px; }
          .logo { font-size: 28px; font-weight: bold; color: #2563eb; margin-bottom: 10px; }
          .tagline { color: #666; font-size: 14px; }
          .user-info { background: #f8fafc; padding: 15px; border-radius: 8px; margin-bottom: 20px; }
          .stats { display: flex; justify-content: space-around; margin: 20px 0; }
          .stat-box { text-align: center; padding: 10px; }
          .stat-number { font-size: 24px; font-weight: bold; color: #2563eb; }
          .stat-label { font-size: 12px; color: #666; }
          .report-item { border: 1px solid #e5e7eb; margin: 10px 0; padding: 15px; border-radius: 8px; }
          .report-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px; }
          .report-title { font-weight: bold; font-size: 16px; }
          .status { padding: 4px 8px; border-radius: 12px; font-size: 12px; font-weight: bold; }
          .status-resolved { background: #dcfce7; color: #166534; }
          .status-progress { background: #fef3c7; color: #92400e; }
          .status-reported { background: #fee2e2; color: #991b1b; }
          .report-details { color: #666; font-size: 14px; }
          .footer { text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #666; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">CivIQ</div>
          <div class="tagline">Empowering Civic Intelligence and Environmental Sustainability</div>
          <h2>Civic Issue Reports Summary</h2>
        </div>
        
        <div class="user-info">
          <h3>User Information</h3>
          <p><strong>Name:</strong> ${reportData.user}</p>
          <p><strong>Email:</strong> ${reportData.email}</p>
          <p><strong>City:</strong> ${reportData.city}</p>
          <p><strong>Report Generated:</strong> ${reportData.generatedAt}</p>
        </div>
        
        <div class="stats">
          <div class="stat-box">
            <div class="stat-number">${reportData.totalReports}</div>
            <div class="stat-label">Total Reports</div>
          </div>
          <div class="stat-box">
            <div class="stat-number">${reportData.resolvedReports}</div>
            <div class="stat-label">Resolved Issues</div>
          </div>
          <div class="stat-box">
            <div class="stat-number">${reportData.totalPoints}</div>
            <div class="stat-label">Points Earned</div>
          </div>
        </div>
        
        <h3>Detailed Reports</h3>
        ${reportData.reports.map(report => `
          <div class="report-item">
            <div class="report-header">
              <div class="report-title">${report.title}</div>
              <span class="status status-${report.status.replace('_', '')}">${report.status.replace('_', ' ').toUpperCase()}</span>
            </div>
            <div class="report-details">
              <p><strong>Category:</strong> ${report.category}</p>
              <p><strong>Description:</strong> ${report.description || 'No description provided'}</p>
              <p><strong>Reported Date:</strong> ${new Date(report.created_at).toLocaleDateString()}</p>
              <p><strong>Points Awarded:</strong> ${report.points_awarded || 15}</p>
              ${report.location ? `<p><strong>Location:</strong> Lat: ${report.location.lat}, Lng: ${report.location.lng}</p>` : ''}
            </div>
          </div>
        `).join('')}
        
        <div class="footer">
          <p>This report was generated by CivIQ - Civic Intelligence Platform</p>
          <p>Thank you for contributing to make your city better!</p>
          <p>© 2024 CivIQ. All rights reserved.</p>
        </div>
      </body>
      </html>
    `

    // Create and download the HTML file
    const blob = new Blob([htmlContent], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `CivIQ_Reports_${reportData.user.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.html`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  useEffect(() => {
    const fetchReports = async () => {
      const { data, error } = await reportsService.getUserReports()
      if (!error && data) {
        setReports(data)
      }
      setLoading(false)
    }
    fetchReports()
  }, [])

  if (loading) return <div className="text-center py-8">Loading your reports...</div>

  return (
    <div>
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-3xl font-bold">My Reports</h1>
        {reports.length > 0 && (
          <button
            onClick={generatePDFReport}
            className="bg-primary-600 text-white px-4 py-2 rounded-lg hover:bg-primary-700 flex items-center space-x-2"
          >
            <span>📄</span>
            <span>Download Report</span>
          </button>
        )}
      </div>
      
      {reports.length > 0 && (
        <div className="bg-white p-4 rounded-lg shadow mb-6">
          <h3 className="font-semibold mb-3">Summary</h3>
          <div className="grid grid-cols-3 gap-4 text-center">
            <div>
              <div className="text-2xl font-bold text-primary-600">{reports.length}</div>
              <div className="text-sm text-gray-600">Total Reports</div>
            </div>
            <div>
              <div className="text-2xl font-bold text-green-600">
                {reports.filter(r => r.status === 'resolved').length}
              </div>
              <div className="text-sm text-gray-600">Resolved</div>
            </div>
            <div>
              <div className="text-2xl font-bold text-yellow-600">
                {reports.reduce((sum, report) => sum + (report.points_awarded || 15), 0)}
              </div>
              <div className="text-sm text-gray-600">Points Earned</div>
            </div>
          </div>
        </div>
      )}
      
      <div className="space-y-4">
        {reports.length === 0 ? (
          <div className="text-center py-8 text-gray-500">
            No reports submitted yet. <a href="/report" className="text-primary-600">Submit your first report</a>
          </div>
        ) : (
          reports.map(report => (
            <div key={report.id} className="bg-white p-6 rounded-lg shadow">
              <div className="flex justify-between items-start">
                <div>
                  <h3 className="text-xl font-semibold mb-2">{report.title}</h3>
                  <p className="text-gray-600 mb-2">{report.category}</p>
                  <p className="text-sm text-gray-500">
                    Reported on {new Date(report.created_at).toLocaleDateString()}
                  </p>
                </div>
                <div className="text-right">
                  <span className={`px-3 py-1 rounded-full text-sm ${
                    report.status === 'resolved' ? 'bg-green-100 text-green-800' :
                    report.status === 'in_progress' ? 'bg-yellow-100 text-yellow-800' :
                    'bg-red-100 text-red-800'
                  }`}>
                    {report.status.replace('_', ' ')}
                  </span>
                  <div className="mt-2 text-primary-600 font-semibold">
                    +{report.points_awarded || 15} points
                  </div>
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  )
}