import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

const translations = {
  en: {
    // Common
    tagline: "Empowering Civic Intelligence and Environmental Sustainability",
    profile: "Profile",
    dashboard: "CivIQ Dashboard",
    quickActions: "Quick Actions",
    reportIssue: "Report Issue",
    map: "Map",
    ngos: "NGOs",
    events: "Events",
    knowledge: "Knowledge",
    quiz: "Quiz",
    login: "Login",
    signup: "Sign Up",
    email: "Email",
    password: "Password",
    name: "Name",
    submit: "Submit",
    cancel: "Cancel",
    save: "Save",
    close: "Close",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    
    // Navigation
    home: "Home",
    about: "About",
    contact: "Contact",
    help: "Help",
    settings: "Settings",
    logout: "Logout",
    
    // Dashboard
    welcomeBack: "Welcome back",
    totalReports: "Total Reports",
    pendingReports: "Pending Reports",
    resolvedReports: "Resolved Reports",
    civilPoints: "Civil Points",
    yourRank: "Your Rank",
    recentActivity: "Recent Activity",
    topContributors: "Top Contributors",
    viewLeaderboard: "View Leaderboard",
    
    // Report Form
    reportTitle: "Report Title",
    description: "Description",
    location: "Location",
    uploadPhoto: "Upload Photo",
    selectCategory: "Select Category",
    roadIssues: "Road Issues",
    wasteManagement: "Waste Management",
    waterIssues: "Water Issues",
    pollution: "Pollution",
    infrastructure: "Infrastructure",
    other: "Other",
    reportSubmitted: "Report submitted successfully!",
    
    // Map
    civicIssuesMap: "Civic Issues Map",
    filterByCategory: "Filter by Category",
    allCategories: "All Categories",
    
    // Quiz
    civicAwarenessQuiz: "Civic Awareness Quiz",
    question: "Question",
    of: "of",
    score: "Score",
    correct: "Correct",
    incorrect: "Incorrect",
    nextQuestion: "Next Question",
    finishQuiz: "Finish Quiz",
    quizComplete: "Quiz Complete!",
    finalScore: "Final Score",
    excellent: "Excellent! You have great civic awareness!",
    goodJob: "Good job! Keep learning about civic issues.",
    keepPracticing: "Keep practicing to improve your civic knowledge!",
    takeQuizAgain: "Take Quiz Again",
    
    // Profile
    myProfile: "My Profile",
    profileInformation: "Profile Information",
    role: "Role",
    city: "City",
    memberSince: "Member Since",
    emailNotifications: "Email Notifications",
    pushNotifications: "Push Notifications",
    privacySettings: "Privacy Settings",
    helpSupport: "Help & Support",
    signOut: "Sign Out",
    
    // Leaderboard
    leaderboard: "Leaderboard",
    rank: "Rank",
    points: "Points",
    reportsCount: "Reports",
    
    // Story Hall
    storiesTitle: "Success Stories & Impact",
    storiesSubtitle: "Celebrating civic heroes and showcasing the real-world impact of community engagement",
    shareStoryTitle: "Share Your Success Story",
    shareStorySubtitle: "Have you made a positive impact in your community? Share your story to inspire others!",
    submitStory: "Submit Your Story",
    storyTitle: "Story Title",
    category: "Category",
    storySummary: "Story Summary",
    impactAchieved: "Impact Achieved",
    shareStoryBtn: "Share Story",
    readFullStory: "Read Full Story →",
    loginToShare: "Please login to share your story",
    storySubmitted: "Story submitted successfully! It will appear in the Knowledge Hub.",
    enterStoryTitle: "Enter your story title",
    tellContribution: "Tell us about your civic contribution...",
    impactExample: "e.g., 100+ residents benefited",
    
    // Footer
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    allRightsReserved: "All rights reserved",
    
    // Admin Dashboard
    adminDashboard: "Admin Dashboard",
    manageReports: "Manage and track civic issue reports",
    overallProgress: "Overall Progress",
    monthlyProgress: "Monthly Progress",
    successRate: "Success Rate",
    reportAnalytics: "Report Analytics",
    allReports: "All Reports",
    issue: "Issue",
    date: "Date",
    status: "Status",
    actions: "Actions",
    reported: "Reported",
    inProgress: "In Progress",
    resolved: "Resolved",
    noReportsFound: "No reports found",
    
    // Knowledge Hub
    knowledgeHub: "Knowledge Hub",
    educationalVideos: "Educational Videos",
    communityContent: "Community Content",
    articles: "Articles",
    upvote: "Upvote",
    comment: "Comment",
    share: "Share"
  },
  hi: {
    // Common
    tagline: "नागरिक बुद्धिमत्ता और पर्यावरणीय स्थिरता को सशक्त बनाना",
    profile: "प्रोफ़ाइल",
    dashboard: "CivIQ डैशबोर्ड",
    quickActions: "त्वरित कार्य",
    reportIssue: "समस्या रिपोर्ट करें",
    map: "मानचित्र",
    ngos: "एनजीओ",
    events: "कार्यक्रम",
    knowledge: "ज्ञान",
    quiz: "प्रश्नोत्तरी",
    login: "लॉगिन",
    signup: "साइन अप",
    email: "ईमेल",
    password: "पासवर्ड",
    name: "नाम",
    submit: "जमा करें",
    cancel: "रद्द करें",
    save: "सेव करें",
    close: "बंद करें",
    loading: "लोड हो रहा है...",
    error: "त्रुटि",
    success: "सफलता",
    
    // Navigation
    home: "होम",
    about: "के बारे में",
    contact: "संपर्क",
    help: "सहायता",
    settings: "सेटिंग्स",
    logout: "लॉगआउट",
    
    // Dashboard
    welcomeBack: "वापस स्वागत है",
    totalReports: "कुल रिपोर्ट्स",
    pendingReports: "लंबित रिपोर्ट्स",
    resolvedReports: "हल की गई रिपोर्ट्स",
    civilPoints: "नागरिक अंक",
    yourRank: "आपकी रैंक",
    recentActivity: "हाल की गतिविधि",
    topContributors: "शीर्ष योगदानकर्ता",
    viewLeaderboard: "लीडरबोर्ड देखें",
    
    // Report Form
    reportTitle: "रिपोर्ट शीर्षक",
    description: "विवरण",
    location: "स्थान",
    uploadPhoto: "फोटो अपलोड करें",
    selectCategory: "श्रेणी चुनें",
    roadIssues: "सड़क की समस्याएं",
    wasteManagement: "कचरा प्रबंधन",
    waterIssues: "पानी की समस्याएं",
    pollution: "प्रदूषण",
    infrastructure: "बुनियादी ढांचा",
    other: "अन्य",
    reportSubmitted: "रिपोर्ट सफलतापूर्वक सबमिट की गई!",
    
    // Map
    civicIssuesMap: "नागरिक समस्याओं का मानचित्र",
    filterByCategory: "श्रेणी के अनुसार फिल्टर करें",
    allCategories: "सभी श्रेणियां",
    
    // Quiz
    civicAwarenessQuiz: "नागरिक जागरूकता प्रश्नोत्तरी",
    question: "प्रश्न",
    of: "का",
    score: "स्कोर",
    correct: "सही",
    incorrect: "गलत",
    nextQuestion: "अगला प्रश्न",
    finishQuiz: "प्रश्नोत्तरी समाप्त करें",
    quizComplete: "प्रश्नोत्तरी पूर्ण!",
    finalScore: "अंतिम स्कोर",
    excellent: "उत्कृष्ट! आपमें बेहतरीन नागरिक जागरूकता है!",
    goodJob: "अच्छा काम! नागरिक मुद्दों के बारे में सीखते रहें।",
    keepPracticing: "अपने नागरिक ज्ञान को बेहतर बनाने के लिए अभ्यास करते रहें!",
    takeQuizAgain: "फिर से प्रश्नोत्तरी लें",
    
    // Profile
    myProfile: "मेरी प्रोफ़ाइल",
    profileInformation: "प्रोफ़ाइल जानकारी",
    role: "भूमिका",
    city: "शहर",
    memberSince: "सदस्य बने",
    emailNotifications: "ईमेल सूचनाएं",
    pushNotifications: "पुश सूचनाएं",
    privacySettings: "गोपनीयता सेटिंग्स",
    helpSupport: "सहायता और समर्थन",
    signOut: "साइन आउट",
    
    // Leaderboard
    leaderboard: "लीडरबोर्ड",
    rank: "रैंक",
    points: "अंक",
    reportsCount: "रिपोर्ट्स",
    
    // Story Hall
    storiesTitle: "सफलता की कहानियां और प्रभाव",
    storiesSubtitle: "नागरिक नायकों का जश्न मनाना और सामुदायिक भागीदारी के वास्तविक प्रभाव को दिखाना",
    shareStoryTitle: "अपनी सफलता की कहानी साझा करें",
    shareStorySubtitle: "क्या आपने अपने समुदाय में सकारात्मक प्रभाव डाला है? दूसरों को प्रेरित करने के लिए अपनी कहानी साझा करें!",
    submitStory: "अपनी कहानी सबमिट करें",
    storyTitle: "कहानी का शीर्षक",
    category: "श्रेणी",
    storySummary: "कहानी का सारांश",
    impactAchieved: "हासिल किया गया प्रभाव",
    shareStoryBtn: "कहानी साझा करें",
    readFullStory: "पूरी कहानी पढ़ें →",
    loginToShare: "कहानी साझा करने के लिए कृपया लॉगिन करें",
    storySubmitted: "कहानी सफलतापूर्वक सबमिट की गई! यह नॉलेज हब में दिखाई देगी।",
    enterStoryTitle: "अपनी कहानी का शीर्षक दर्ज करें",
    tellContribution: "हमें अपने नागरिक योगदान के बारे में बताएं...",
    impactExample: "उदा. 100+ निवासियों को लाभ हुआ",
    
    // Footer
    privacyPolicy: "गोपनीयता नीति",
    termsOfService: "सेवा की शर्तें",
    allRightsReserved: "सभी अधिकार सुरक्षित",
    
    // Admin Dashboard
    adminDashboard: "एडमिन डैशबोर्ड",
    manageReports: "नागरिक समस्या रिपोर्ट्स का प्रबंधन और ट्रैकिंग",
    overallProgress: "समग्र प्रगति",
    monthlyProgress: "मासिक प्रगति",
    successRate: "सफलता दर",
    reportAnalytics: "रिपोर्ट एनालिटिक्स",
    allReports: "सभी रिपोर्ट्स",
    issue: "समस्या",
    date: "तारीख",
    status: "स्थिति",
    actions: "कार्य",
    reported: "रिपोर्ट की गई",
    inProgress: "प्रगति में",
    resolved: "हल हो गई",
    noReportsFound: "कोई रिपोर्ट नहीं मिली",
    
    // Knowledge Hub
    knowledgeHub: "नॉलेज हब",
    educationalVideos: "शैक्षिक वीडियो",
    communityContent: "सामुदायिक सामग्री",
    articles: "लेख",
    upvote: "अपवोट",
    comment: "टिप्पणी",
    share: "साझा करें"
  },
  bn: {
    // Common
    tagline: "নাগরিক বুদ্ধিমত্তা এবং পরিবেশগত স্থিতিশীলতা ক্ষমতায়ন",
    profile: "প্রোফাইল",
    dashboard: "CivIQ ড্যাশবোর্ড",
    quickActions: "দ্রুত কর্ম",
    reportIssue: "সমস্যা রিপোর্ট করুন",
    map: "মানচিত্র",
    ngos: "এনজিও",
    events: "ইভেন্ট",
    knowledge: "জ্ঞান",
    quiz: "কুইজ",
    login: "লগইন",
    signup: "সাইন আপ",
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    name: "নাম",
    submit: "জমা দিন",
    cancel: "বাতিল",
    save: "সেভ",
    close: "বন্ধ",
    loading: "লোড হচ্ছে...",
    error: "ত্রুটি",
    success: "সফলতা",
    
    // Navigation
    home: "হোম",
    about: "সম্পর্কে",
    contact: "যোগাযোগ",
    help: "সাহায্য",
    settings: "সেটিংস",
    logout: "লগআউট",
    
    // Dashboard
    welcomeBack: "ফিরে এসেছেন স্বাগতম",
    totalReports: "মোট রিপোর্ট",
    pendingReports: "বিচারাধীন রিপোর্ট",
    resolvedReports: "সমাধানকৃত রিপোর্ট",
    civilPoints: "নাগরিক পয়েন্ট",
    yourRank: "আপনার র্যাঙ্ক",
    recentActivity: "সাম্প্রতিক কার্যকলাপ",
    topContributors: "শীর্ষ অবদানকারী",
    viewLeaderboard: "লিডারবোর্ড দেখুন",
    
    // Report Form
    reportTitle: "রিপোর্টের শিরোনাম",
    description: "বর্ণনা",
    location: "অবস্থান",
    uploadPhoto: "ছবি আপলোড করুন",
    selectCategory: "বিভাগ নির্বাচন করুন",
    roadIssues: "রাস্তার সমস্যা",
    wasteManagement: "আবর্জনা ব্যবস্থাপনা",
    waterIssues: "পানির সমস্যা",
    pollution: "দূষণ",
    infrastructure: "অবকাঠামো",
    other: "অন্যান্য",
    reportSubmitted: "রিপোর্ট সফলভাবে জমা দেওয়া হয়েছে!",
    
    // Map
    civicIssuesMap: "নাগরিক সমস্যার ম্যাপ",
    filterByCategory: "বিভাগ অনুযায়ী ফিল্টার করুন",
    allCategories: "সব বিভাগ",
    
    // Quiz
    civicAwarenessQuiz: "নাগরিক সচেতনতা কুইজ",
    question: "প্রশ্ন",
    of: "এর",
    score: "স্কোর",
    correct: "সঠিক",
    incorrect: "ভুল",
    nextQuestion: "পরবর্তী প্রশ্ন",
    finishQuiz: "কুইজ শেষ করুন",
    quizComplete: "কুইজ সম্পূর্ণ!",
    finalScore: "চূড়ান্ত স্কোর",
    excellent: "চমৎকার! আপনার দুর্দান্ত নাগরিক সচেতনতা আছে!",
    goodJob: "ভাল কাজ! নাগরিক বিষয়ে শিখতে থাকুন।",
    keepPracticing: "আপনার নাগরিক জ্ঞান বাড়াতে অভ্যাস চালিয়ে যান!",
    takeQuizAgain: "আবার কুইজ নিন",
    
    // Profile
    myProfile: "আমার প্রোফাইল",
    profileInformation: "প্রোফাইলের তথ্য",
    role: "ভূমিকা",
    city: "শহর",
    memberSince: "সদস্য হয়েছেন",
    emailNotifications: "ইমেইল বিজ্ঞপ্তি",
    pushNotifications: "পুশ বিজ্ঞাপ্তি",
    privacySettings: "গোপনীয়তা সেটিংস",
    helpSupport: "সাহায্য ও সহায়তা",
    signOut: "সাইন আউট",
    
    // Leaderboard
    leaderboard: "লিডারবোর্ড",
    rank: "র্যাঙ্ক",
    points: "পয়েন্ট",
    reportsCount: "রিপোর্ট",
    
    // Story Hall
    storiesTitle: "সফলতার গল্প ও প্রভাব",
    storiesSubtitle: "নাগরিক বীরদের উদযাপন ও সমুদায়িক অংশগ্রহণের বাস্তব প্রভাব প্রদর্শন",
    shareStoryTitle: "আপনার সফলতার গল্প শেয়ার করুন",
    shareStorySubtitle: "আপনি কি আপনার সমুদায়ে ইতিবাচক প্রভাব ফেলেছেন? অন্যদের অনুপ্রাণিত করতে আপনার গল্প শেয়ার করুন!",
    submitStory: "আপনার গল্প জমা দিন",
    storyTitle: "গল্পের শিরোনাম",
    category: "বিভাগ",
    storySummary: "গল্পের সারাংশ",
    impactAchieved: "অর্জিত প্রভাব",
    shareStoryBtn: "গল্প শেয়ার করুন",
    readFullStory: "পূর্ণ গল্প পড়ুন →",
    loginToShare: "গল্প শেয়ার করতে দয়া করে লগইন করুন",
    storySubmitted: "গল্প সফলভাবে জমা দেওয়া হয়েছে! এটি জ্ঞান হাবে দেখা যাবে।",
    enterStoryTitle: "আপনার গল্পের শিরোনাম লিখুন",
    tellContribution: "আমাদের আপনার নাগরিক অবদানের কথা বলুন...",
    impactExample: "যেমন, ১০০+ বাসিন্দা উপকৃত হয়েছে",
    
    // Footer
    privacyPolicy: "গোপনীয়তা নীতি",
    termsOfService: "সেবার শর্তাবলী",
    allRightsReserved: "সব অধিকার সংরক্ষিত",
    
    // Admin Dashboard
    adminDashboard: "অ্যাডমিন ড্যাশবোর্ড",
    manageReports: "নাগরিক সমস্যা রিপোর্ট পরিচালনা ও ট্র্যাকিং",
    overallProgress: "সমগ্র অগ্রগতি",
    monthlyProgress: "মাসিক অগ্রগতি",
    successRate: "সফলতার হার",
    reportAnalytics: "রিপোর্ট বিশ্লেষণ",
    allReports: "সব রিপোর্ট",
    issue: "সমস্যা",
    date: "তারিখ",
    status: "অবস্থা",
    actions: "কার্যকলাপ",
    reported: "রিপোর্ট করা হয়েছে",
    inProgress: "প্রগতিশীল",
    resolved: "সমাধান হয়েছে",
    noReportsFound: "কোনো রিপোর্ট পাওয়া যায়নি",
    
    // Knowledge Hub
    knowledgeHub: "জ্ঞান হাব",
    educationalVideos: "শিক্ষামূলক ভিডিও",
    communityContent: "সমুদায়িক বিষয়বস্তু",
    articles: "নিবন্ধ",
    upvote: "আপভোট",
    comment: "মন্তব্য",
    share: "শেয়ার করুন"
  },
  te: {
    tagline: "పౌర మేధస్సు మరియు పరిసర స్థిరత్వాన్ని శక్తివంతం చేయడం",
    profile: "ప్రొఫైల్",
    dashboard: "CivIQ డాష్బోర్డ్",
    quickActions: "త్వరిత చర్యలు",
    reportIssue: "సమస్యను నివేదించండి",
    map: "మ్యాప్",
    ngos: "ఎన్జిఓలు",
    events: "ఈవెంట్లు",
    knowledge: "జ్ఞానం",
    quiz: "క్విజ్",
    login: "లాగిన్",
    signup: "సైన్ అప్",
    email: "ఇమెయిల్",
    password: "పాస్వర్డ్",
    name: "పేరు",
    submit: "సమర్పించు",
    cancel: "రద్దు",
    save: "సేవ్",
    close: "మూసివేయి",
    loading: "లోడ్ అవుతోంది...",
    error: "తప్పు",
    success: "విజయం",
    home: "హోమ్",
    about: "గురించి",
    contact: "సంపర్కం",
    help: "సహాయం",
    settings: "సెట్టింగ్లు",
    logout: "లాగ్ఆఉట్",
    welcomeBack: "మళ్లీ వచ్చినందుకు స్వాగతం",
    totalReports: "మొత్తం రిపోర్ట్లు",
    pendingReports: "పెండింగ్ రిపోర్ట్లు",
    resolvedReports: "పరిష్కరించిన రిపోర్ట్లు",
    civilPoints: "పౌర పాయింట్లు",
    yourRank: "మీ రాంక్",
    recentActivity: "ఇక్కడ కార్యకలాపాలు",
    topContributors: "ప్రముఖ కొత్తదారులు",
    viewLeaderboard: "లీడర్బోర్డ్ చూడండి",
    reportTitle: "రిపోర్ట్ శీర్షిక",
    description: "వివరణ",
    location: "స్థానం",
    uploadPhoto: "ఫోటో అప్లోడ్ చేయండి",
    selectCategory: "వర్గం ఎన్నుకోండి",
    roadIssues: "రోడ్డు సమస్యలు",
    wasteManagement: "వేస్ట్ మ్యానేజ్మెంట్",
    waterIssues: "నీరు సమస్యలు",
    pollution: "ప్రదూషణ",
    infrastructure: "ఇన్ఫ్రాస్ట్రక్చర్",
    other: "ఇతరం",
    reportSubmitted: "రిపోర్ట్ విజయవంతంగా సమర్పించబడింది!",
    civicIssuesMap: "పౌర సమస్యల మ్యాప్",
    filterByCategory: "వర్గం ప్రకారం ఫిల్టర్ చేయండి",
    allCategories: "అన్ని వర్గాలు",
    civicAwarenessQuiz: "పౌర అవగాహన క్విజ్",
    question: "ప్రశ్న",
    of: "లో",
    score: "స్కోర్",
    correct: "సరైనది",
    incorrect: "తప్పు",
    nextQuestion: "తరువాత ప్రశ్న",
    finishQuiz: "క్విజ్ ముగించండి",
    quizComplete: "క్విజ్ పూర్తి!",
    finalScore: "అంతిమ స్కోర్",
    excellent: "అద్భుతం! మీకు మెల్లగా పౌర అవగాహన ఉంది!",
    goodJob: "మెల్లగా చేశారు! పౌర విషయాల గురించి నేర్చుకొన్డి వెళ్ళండి।",
    keepPracticing: "మీ పౌర జ్ఞానాన్ని మెంపరచేసుకోవడానికి అభ్యాసం చేస్తూ ఉండండి!",
    takeQuizAgain: "మళ్లీ క్విజ్ తీసుకోండి",
    myProfile: "నా ప్రొఫైల్",
    profileInformation: "ప్రొఫైల్ సమాచారం",
    role: "పాత్ర",
    city: "నగరం",
    memberSince: "సభ్యుడాయిన తేదీ",
    emailNotifications: "ఇమెయిల్ నోటిఫికేషన్లు",
    pushNotifications: "పుష్ నోటిఫికేషన్లు",
    privacySettings: "గోప్యత సెట్టింగ్లు",
    helpSupport: "సహాయం మరియు మద్దతు",
    signOut: "సైన్ ఆఉట్",
    leaderboard: "లీడర్బోర్డ్",
    rank: "రాంక్",
    points: "పాయింట్లు",
    reportsCount: "రిపోర్ట్లు",
    storiesTitle: "విజయ కథలు మరియు ప్రభావం",
    storiesSubtitle: "పౌర వీరులను సన్మానించడం మరియు సముదాయ భాగీదారి వాస్తవ ప్రభావాన్ని ప్రదర్శించడం",
    shareStoryTitle: "మీ విజయ కథను పంచుకోండి",
    shareStorySubtitle: "మీరు మీ సముదాయంలో మెల్లగా ప్రభావం చేశారా? ఇతరులను ప్రేరేపించడానికి మీ కథను పంచుకోండి!",
    submitStory: "మీ కథను సమర్పించండి",
    storyTitle: "కథ శీర్షిక",
    category: "వర్గం",
    storySummary: "కథ సారాంశం",
    impactAchieved: "సాధించిన ప్రభావం",
    shareStoryBtn: "కథను పంచుకోండి",
    readFullStory: "ముందు కథను చదవండి →",
    loginToShare: "కథను పంచుకోవడానికి దయచేసి లాగిన్ అవ్వండి",
    storySubmitted: "కథ విజయవంతంగా సమర్పించబడింది! ఇది నాలెడ్జ్ హబ్లో కనిపిస్తుంది।",
    enterStoryTitle: "మీ కథ శీర్షికను రాయండి",
    tellContribution: "మీ పౌర యోగదానం గురించి మాకు చెప్పండి...",
    impactExample: "ఉదా. 100+ నివాసులకు ప్రయోజనం అయ్యింది",
    privacyPolicy: "గోప్యత నీతి",
    termsOfService: "సేవా నిబంధనలు",
    allRightsReserved: "అన్ని అధికారాలు రక్షితం",
    adminDashboard: "అడ్మిన్ డాష్బోర్డ్",
    manageReports: "పౌర సమస్య రిపోర్ట్ల పరిపాలన మరియు ట్రాకింగ్",
    overallProgress: "మొత్తం ప్రగతి",
    monthlyProgress: "నెలవారీ ప్రగతి",
    successRate: "విజయ రేటు",
    reportAnalytics: "రిపోర్ట్ విశ్లేషణలు",
    allReports: "అన్ని రిపోర్ట్లు",
    issue: "సమస్య",
    date: "తేదీ",
    status: "స్థితి",
    actions: "కార్యాలు",
    reported: "రిపోర్ట్ చేయబడింది",
    inProgress: "ప్రగతిలో ఉంది",
    resolved: "పరిష్కరించబడింది",
    noReportsFound: "ఎవరు రిపోర్ట్లు కనుగొనబడలేదు",
    knowledgeHub: "నాలెడ్జ్ హబ్",
    educationalVideos: "విద్యా వీడియోలు",
    communityContent: "సముదాయ విషయాలు",
    articles: "లేఖలు",
    upvote: "అప్వోట్",
    comment: "కామెంట్",
    share: "పంచుకోండి"
  },
  ta: {
    tagline: "குடிமக்கள் அறிவுத்திறனை மற்றும் சுற்றுச்சூழல் நிலைத்தன்மையை வலுப்படுத்துதல்",
    profile: "சுயவிவரம்",
    dashboard: "CivIQ டாஷ்போர்டு",
    quickActions: "விரைவு செயல்கள்",
    reportIssue: "பிரச்சினையை புகாரளிக்கவும்",
    map: "வரைபடம்",
    ngos: "என்ஜிஓக்கள்",
    events: "நிகழ்வுகள்",
    knowledge: "அறிவு",
    quiz: "வினாடி வினா",
    login: "உள்நுழைய",
    signup: "பதிவு செய்க",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    name: "பெயர்",
    submit: "சமர்ப்பிக்க",
    cancel: "ரத்து",
    save: "சேமி",
    close: "மூடு",
    loading: "லோட் ஆகிக்கொண்டிருக்கிறது...",
    error: "பிழை",
    success: "வெற்றி",
    home: "வீடு",
    about: "பற்றி",
    contact: "தொடர்பு",
    help: "உதவி",
    settings: "அமைப்புகள்",
    logout: "வெளியேறு",
    welcomeBack: "மீண்டும் வரவேற்பு",
    totalReports: "முழு அறிக்கைகள்",
    pendingReports: "நிலுவையில் உள்ள அறிக்கைகள்",
    resolvedReports: "தீர்க்கப்பட்ட அறிக்கைகள்",
    civilPoints: "குடிமக்கள் புள்ளிகள்",
    yourRank: "உங்கள் தரம்",
    recentActivity: "இற்கைய செயல்பாடு",
    topContributors: "முதல் பங்காளிப்பாளர்கள்",
    viewLeaderboard: "தலைவர் பட்டியலை பார்க்கவும்",
    reportTitle: "அறிக்கை தலைப்பு",
    description: "விவரணை",
    location: "இடம்",
    uploadPhoto: "படம் பதிவேற்றவும்",
    selectCategory: "வகையை தேர்ந்தெடுக்கவும்",
    roadIssues: "சாலை பிரச்சினைகள்",
    wasteManagement: "கருதல் மேலாண்மை",
    waterIssues: "நீர் பிரச்சினைகள்",
    pollution: "மலினீகரணம்",
    infrastructure: "அடிப்படை வசதி",
    other: "மற்றவை",
    reportSubmitted: "அறிக்கை வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!",
    civicIssuesMap: "குடிமக்கள் பிரச்சினைகள் வரைபடம்",
    filterByCategory: "வகை அடிப்படையில் வடிகட்டவும்",
    allCategories: "அனைத்து வகைகள்",
    civicAwarenessQuiz: "குடிமக்கள் விழிப்புணர்வு வினாடி வினா",
    question: "கேள்வி",
    of: "இல்",
    score: "மதிப்பெண்",
    correct: "சரி",
    incorrect: "தவறு",
    nextQuestion: "அடுத்த கேள்வி",
    finishQuiz: "வினாடி வினாவை முடிக்கவும்",
    quizComplete: "வினாடி வினா முடிந்தது!",
    finalScore: "இறுதி மதிப்பெண்",
    excellent: "சிறப்பு! உங்களிடம் சிறந்த குடிமக்கள் விழிப்புணர்வு உள்ளது!",
    goodJob: "நல்ல வேலை! குடிமக்கள் பிரச்சினைகளை பற்றி கற்றுக்கொண்டே இருங்கள்।",
    keepPracticing: "உங்கள் குடிமக்கள் அறிவை மேம்படுத்த பழக்கத்தை தொடர்ந்து கொண்டே இருங்கள்!",
    takeQuizAgain: "மீண்டும் வினாடி வினா எடுங்கள்",
    myProfile: "என் சுயவிவரம்",
    profileInformation: "சுயவிவர தகவல்",
    role: "பங்கு",
    city: "நகரம்",
    memberSince: "உறுப்பினரான நாள்",
    emailNotifications: "மின்னஞ்சல் அறிவிப்புகள்",
    pushNotifications: "துரித அறிவிப்புகள்",
    privacySettings: "தனியுரிமை அமைப்புகள்",
    helpSupport: "உதவி மற்றும் ஆதரவு",
    signOut: "வெளியேறு",
    leaderboard: "தலைவர் பட்டியல்",
    rank: "தரம்",
    points: "புள்ளிகள்",
    reportsCount: "அறிக்கைகள்",
    storiesTitle: "வெற்றி கதைகள் மற்றும் தாக்கம்",
    storiesSubtitle: "குடிமக்கள் வீரர்களை கொண்டாடுவது மற்றும் சமுதாய பங்கேற்பின் நிஜமான தாக்கத்தை வெளிப்படுத்துவது",
    shareStoryTitle: "உங்கள் வெற்றி கதையை பகிரவும்",
    shareStorySubtitle: "நீங்கள் உங்கள் சமுதாயத்தில் நல்ல தாக்கத்தை ஏற்படுத்தியிருக்கிறீர்களா? மற்றவர்களை ஊக்குவிக்க உங்கள் கதையை பகிரவும்!",
    submitStory: "உங்கள் கதையை சமர்ப்பிக்கவும்",
    storyTitle: "கதை தலைப்பு",
    category: "வகை",
    storySummary: "கதை சுருக்கம்",
    impactAchieved: "அடைந்த தாக்கம்",
    shareStoryBtn: "கதையை பகிரவும்",
    readFullStory: "முழு கதையை படிக்கவும் →",
    loginToShare: "கதையை பகிர தயவு செய்து உள்நுழையவும்",
    storySubmitted: "கதை வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது! இது அறிவு மையத்தில் தேன்றும்।",
    enterStoryTitle: "உங்கள் கதை தலைப்பை உள்ளிடவும்",
    tellContribution: "உங்கள் குடிமக்கள் பங்களிப்பை பற்றி எங்களிடம் சொல்லவும்...",
    impactExample: "உதா. 100+ குடியிருப்பாளர்கள் பயனடைந்தனர்",
    privacyPolicy: "தனியுரிமை கொள்கை",
    termsOfService: "சேவை விதிமுறைகள்",
    allRightsReserved: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை",
    adminDashboard: "நிர்வாகி டாஷ்போர்டு",
    manageReports: "குடிமக்கள் பிரச்சினை அறிக்கைகள் மேலாண்மை மற்றும் கக்கம்",
    overallProgress: "முழு மை முன்னேற்றம்",
    monthlyProgress: "மாதாந்திர முன்னேற்றம்",
    successRate: "வெற்றி விகிதம்",
    reportAnalytics: "அறிக்கை பகுப்பாய்வு",
    allReports: "அனைத்து அறிக்கைகள்",
    issue: "பிரச்சினை",
    date: "தேதி",
    status: "நிலை",
    actions: "செயல்கள்",
    reported: "அறிவிக்கப்பட்டது",
    inProgress: "நடைபெறுகிறது",
    resolved: "தீர்க்கப்பட்டது",
    noReportsFound: "எந்த அறிக்கையும் காணவில்லை",
    knowledgeHub: "அறிவு மையம்",
    educationalVideos: "கல்வி வீடியோகள்",
    communityContent: "சமுதாய உள்ளடக்கம்",
    articles: "கட்டுரைகள்",
    upvote: "மேல் வோட்டு",
    comment: "கருத்து",
    share: "பகிரவும்"
  },
  kn: {
    tagline: "ನಾಗರಿಕ ಬುದ್ಧಿವಂತಿಕೆ ಮತ್ತು ಪರಿಸರ ಸ್ಥಿರತೆಯನ್ನು ಸಶಕ್ತಗೊಳಿಸುವುದು",
    profile: "ಪ್ರೊಫೈಲ್",
    dashboard: "CivIQ ಡ್ಯಾಶ್ಬೋರ್ಡ್",
    quickActions: "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
    reportIssue: "ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ",
    map: "ನಕ್ಷೆ",
    ngos: "ಎನ್ಜಿಒಗಳು",
    events: "ಈವೆಂಟ್ಗಳು",
    knowledge: "ಜ್ಞಾನ",
    quiz: "ಕ್ವಿಜ್",
    login: "ಲಾಗಿನ್",
    signup: "ಸೈನ್ ಅಪ್",
    email: "ಇಮೇಲ್",
    password: "ಪಾಸ್ವರ್ಡ್",
    name: "ಹೆಸರು",
    submit: "ಸಲ್ಲಿಸಿ",
    cancel: "ರದ್ದುಗೊಳಿಸಿ",
    save: "ಉಳಿಸಿ",
    close: "ಮುಚ್ಚಿ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    error: "ತಪ್ಪು",
    success: "ಯಶಸ್ಸು",
    home: "ಮನೆ",
    about: "ಕುರಿತು",
    contact: "ಸಂಪರ್ಕ",
    help: "ಸಹಾಯ",
    settings: "ಸೆಟ್ಟಿಂಗ್ಗಳು",
    logout: "ಲಾಗ್ಆಉಟ್",
    welcomeBack: "ಮತ್ತೆ ಸ್ವಾಗತ",
    totalReports: "ಮೊತ್ತ ರಿಪೋರ್ಟ್ಗಳು",
    pendingReports: "ಪೆಂಡಿಂಗ್ ರಿಪೋರ್ಟ್ಗಳು",
    resolvedReports: "ಸಮಾಧಾನವಾದ ರಿಪೋರ್ಟ್ಗಳು",
    civilPoints: "ನಾಗರಿಕ ಅಂಕಗಳು",
    yourRank: "ನಿಮ್ಮ ರ್ಯಾಂಕ್",
    recentActivity: "ಇದೀಗಿನ ಚಾಲನೆ",
    topContributors: "ಪ್ರಮುಖ ಯೋಗದಾನಗಾರರು",
    viewLeaderboard: "ಲೀಡರ್ಬೋರ್ಡ್ ನೋಡಿ",
    reportTitle: "ರಿಪೋರ್ಟ್ ಶೀರ್ಷಿಕೆ",
    description: "ವಿವರಣೆ",
    location: "ಸ್ಥಳ",
    uploadPhoto: "ಫೋಟೋ ಅಪ್ಲೋಡ್ ಮಾಡಿ",
    selectCategory: "ವರ್ಗ ಆಯ್ಕೆ ಮಾಡಿ",
    roadIssues: "ರಸ್ತೆ ಸಮಸ್ಯೆಗಳು",
    wasteManagement: "ಕಚರ ವ್ಯವಸ್ಥಾಪನೆ",
    waterIssues: "ನೀರಿನ ಸಮಸ್ಯೆಗಳು",
    pollution: "ದೂಷಣೆ",
    infrastructure: "ಅಧಾರಭೂತ ಸುವಿಧೆ",
    other: "ಇತರೆ",
    reportSubmitted: "ರಿಪೋರ್ಟ್ ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ!",
    civicIssuesMap: "ನಾಗರಿಕ ಸಮಸ್ಯೆಗಳ ನಕ್ಷೆ",
    filterByCategory: "ವರ್ಗದ ಅನುಸಾರ ಫಿಲ್ಟರ್ ಮಾಡಿ",
    allCategories: "ಎಲ್ಲಾ ವರ್ಗಗಳು",
    civicAwarenessQuiz: "ನಾಗರಿಕ ಜಾಗೃತಿ ಕ್ವಿಜ್",
    question: "ಪ್ರಶ್ನೆ",
    of: "ರಲ್ಲಿ",
    score: "ಅಂಕ",
    correct: "ಸರಿ",
    incorrect: "ತಪ್ಪು",
    nextQuestion: "ಮುಂದಿನ ಪ್ರಶ್ನೆ",
    finishQuiz: "ಕ್ವಿಜ್ ಮುಗಿಸಿ",
    quizComplete: "ಕ್ವಿಜ್ ಪೂರ್ಣಗೊಂಡಿದೆ!",
    finalScore: "ಅಂತಿಮ ಅಂಕ",
    excellent: "ಅದ್ಭುತ! ನಿಮಗೆ ಉತ್ತಮ ನಾಗರಿಕ ಜಾಗೃತಿ ಇದೆ!",
    goodJob: "ಚೆನ್ನಾಗಿ ಮಾಡಿದ್ದೀರಿ! ನಾಗರಿಕ ವಿಷಯಗಳ ಕುರಿತು ಕಲಿಯುತ್ತಿರಿ।",
    keepPracticing: "ನಿಮ್ಮ ನಾಗರಿಕ ಜ್ಞಾನವನ್ನು ಸುಧಾರಿಸಲು ಅಭ್ಯಾಸ ಮಾಡುತ್ತಿರಿ!",
    takeQuizAgain: "ಮತ್ತೆ ಕ್ವಿಜ್ ತಗೊಳ್ಳಿ",
    myProfile: "ನನ್ನ ಪ್ರೊಫೈಲ್",
    profileInformation: "ಪ್ರೊಫೈಲ್ ಮಾಹಿತಿ",
    role: "ಭೂಮಿಕೆ",
    city: "ನಗರ",
    memberSince: "ಸದಸ್ಯರಾದ ದಿನಾಂಕ",
    emailNotifications: "ಇಮೇಲ್ ಅವಗತಿಗಳು",
    pushNotifications: "ಪುಷ್ ಅವಗತಿಗಳು",
    privacySettings: "ಗೌಪ್ಯತೆ ಸೆಟ್ಟಿಂಗ್ಗಳು",
    helpSupport: "ಸಹಾಯ ಮತ್ತು ಸಹಾಯತೆ",
    signOut: "ಸೈನ್ ಆಉಟ್",
    leaderboard: "ಲೀಡರ್ಬೋರ್ಡ್",
    rank: "ರ್ಯಾಂಕ್",
    points: "ಅಂಕಗಳು",
    reportsCount: "ರಿಪೋರ್ಟ್ಗಳು"
  },
  mr: {
    tagline: "नागरी बुद्धिमत्ता सक्षम करणे",
    profile: "प्रोफाइल",
    dashboard: "CivIQ डॅशबोर्ड",
    quickActions: "त्वरित कृती",
    reportIssue: "समस्या नोंदवा",
    map: "नकाशा",
    ngos: "एनजीओ",
    events: "कार्यक्रम",
    knowledge: "ज्ञान",
    quiz: "प्रश्नमंजुषा",
    login: "लॉगिन",
    signup: "साइन अप",
    email: "ईमेल",
    password: "पासवर्ड",
    name: "नाव",
    submit: "सबमिट",
    cancel: "रद्द",
    save: "सेव्ह",
    close: "बंद"
  }
}

const languages = [
  { code: 'en', name: 'English' },
  { code: 'hi', name: 'हिन्दी' },
  { code: 'bn', name: 'বাংলা' },
  { code: 'te', name: 'తెలుగు' },
  { code: 'ta', name: 'தமிழ்' },
  { code: 'kn', name: 'ಕನ್ನಡ' },
  { code: 'mr', name: 'मराठी' }
]

export function LanguageProvider({ children }) {
  const [currentLanguage, setCurrentLanguage] = useState('en')

  useEffect(() => {
    const savedLanguage = localStorage.getItem('civiq_language')
    if (savedLanguage && translations[savedLanguage]) {
      setCurrentLanguage(savedLanguage)
    }
  }, [])

  const changeLanguage = (langCode) => {
    setCurrentLanguage(langCode)
    localStorage.setItem('civiq_language', langCode)
  }

  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations.en[key] || key
  }

  return (
    <LanguageContext.Provider value={{
      currentLanguage,
      changeLanguage,
      t,
      languages
    }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}